### .github/workflows/github-actions-02.yml

name: Test GitHub Actions-02
run-name: Run GitHub Actions-02
on:
#  push:
#    branches:
#      - main
  workflow_dispatch

jobs:
  Test-GitHub-Actions:
    runs-on: ubuntu-latest
    steps:
      - name: echo-02
        run: |
          echo "test echo-02"
