### github-action-variable-04.yml

name: Test Github Actions Variable-04
run-name: Github Actions inputs, outputs, needs
on:
  workflow_dispatch:
    inputs:
      name:
        description: '이름'
        required: true
        default: '유진'

jobs:
  input-data:
    runs-on: ubuntu-latest
    steps:
      - name: Print input data
        run: echo "Hello, ${{ github.event.inputs.name }}"

