### github-action-variable-03.yml

name: Test Github Actions Variable-03
run-name: Github Actions var, secret
on:
  workflow_dispatch

jobs:
  check-vars-context:
    runs-on: ubuntu-latest
    steps:
      - name: "Hello Var Test"
        run: echo "Hello ${{ vars.VAR_TEST }}"

  check-secrets-context:
    runs-on: ubuntu-latest
    steps:
      - name: "Hello Secret Test"
        run: echo "Hello ${{ secrets.SECRET_TEST }}"
      
