### github-action-jobs-01.yml

name: Test Github Actions Jobs 01
run-name: Github Actions jobs
on:
  push

jobs:
  job1:
    runs-on: ubuntu-latest
    steps:
      - run: echo ${{ github.job }}
  job2:
    runs-on: ubuntu-latest
    needs: job1
    steps:
      - run: echo ${{ github.job }}
  job3:
    runs-on: ubuntu-latest
    needs: [job1, job2]
    steps:
      - run: echo ${{ github.job }}
